// Code generated by protoc-gen-go.
// source: project.proto
// DO NOT EDIT!

/*
Package crypto_pb is a generated protocol buffer package.

It is generated from these files:
	project.proto

It has these top-level messages:
	ProjectCredentialOperation
	ProjectOperation
	Operation
	Credential
	Project
	ProjectOperationResponse
	CredentialOperationResponse
	Response
*/
package crypto_pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ProjectCredentialOperation_Command int32

const (
	ProjectCredentialOperation_GET    ProjectCredentialOperation_Command = 0
	ProjectCredentialOperation_SET    ProjectCredentialOperation_Command = 1
	ProjectCredentialOperation_DELETE ProjectCredentialOperation_Command = 2
)

var ProjectCredentialOperation_Command_name = map[int32]string{
	0: "GET",
	1: "SET",
	2: "DELETE",
}
var ProjectCredentialOperation_Command_value = map[string]int32{
	"GET":    0,
	"SET":    1,
	"DELETE": 2,
}

func (x ProjectCredentialOperation_Command) String() string {
	return proto.EnumName(ProjectCredentialOperation_Command_name, int32(x))
}
func (ProjectCredentialOperation_Command) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor0, []int{0, 0}
}

type ProjectOperation_Command int32

const (
	ProjectOperation_CREATE           ProjectOperation_Command = 0
	ProjectOperation_UPDATE           ProjectOperation_Command = 1
	ProjectOperation_DELETE           ProjectOperation_Command = 2
	ProjectOperation_ADD_MEMBER       ProjectOperation_Command = 3
	ProjectOperation_DELETE_MEMBER    ProjectOperation_Command = 4
	ProjectOperation_LIST_CREDENTIALS ProjectOperation_Command = 5
)

var ProjectOperation_Command_name = map[int32]string{
	0: "CREATE",
	1: "UPDATE",
	2: "DELETE",
	3: "ADD_MEMBER",
	4: "DELETE_MEMBER",
	5: "LIST_CREDENTIALS",
}
var ProjectOperation_Command_value = map[string]int32{
	"CREATE":           0,
	"UPDATE":           1,
	"DELETE":           2,
	"ADD_MEMBER":       3,
	"DELETE_MEMBER":    4,
	"LIST_CREDENTIALS": 5,
}

func (x ProjectOperation_Command) String() string {
	return proto.EnumName(ProjectOperation_Command_name, int32(x))
}
func (ProjectOperation_Command) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{1, 0} }

type Response_Status int32

const (
	Response_ERROR   Response_Status = 0
	Response_SUCCESS Response_Status = 1
)

var Response_Status_name = map[int32]string{
	0: "ERROR",
	1: "SUCCESS",
}
var Response_Status_value = map[string]int32{
	"ERROR":   0,
	"SUCCESS": 1,
}

func (x Response_Status) String() string {
	return proto.EnumName(Response_Status_name, int32(x))
}
func (Response_Status) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{7, 0} }

type ProjectCredentialOperation struct {
	Command ProjectCredentialOperation_Command `protobuf:"varint,1,opt,name=command,enum=crypto_pb.ProjectCredentialOperation_Command" json:"command,omitempty"`
	Project int32                              `protobuf:"varint,2,opt,name=project" json:"project,omitempty"`
	Key     string                             `protobuf:"bytes,3,opt,name=key" json:"key,omitempty"`
	Value   string                             `protobuf:"bytes,4,opt,name=value" json:"value,omitempty"`
}

func (m *ProjectCredentialOperation) Reset()                    { *m = ProjectCredentialOperation{} }
func (m *ProjectCredentialOperation) String() string            { return proto.CompactTextString(m) }
func (*ProjectCredentialOperation) ProtoMessage()               {}
func (*ProjectCredentialOperation) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type ProjectOperation struct {
	Command     ProjectOperation_Command `protobuf:"varint,1,opt,name=command,enum=crypto_pb.ProjectOperation_Command" json:"command,omitempty"`
	Name        string                   `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Environment string                   `protobuf:"bytes,3,opt,name=environment" json:"environment,omitempty"`
	ProjectId   int32                    `protobuf:"varint,4,opt,name=projectId" json:"projectId,omitempty"`
	MemberId    int32                    `protobuf:"varint,5,opt,name=memberId" json:"memberId,omitempty"`
	UserId      int32                    `protobuf:"varint,6,opt,name=userId" json:"userId,omitempty"`
	AccessLevel string                   `protobuf:"bytes,7,opt,name=accessLevel" json:"accessLevel,omitempty"`
}

func (m *ProjectOperation) Reset()                    { *m = ProjectOperation{} }
func (m *ProjectOperation) String() string            { return proto.CompactTextString(m) }
func (*ProjectOperation) ProtoMessage()               {}
func (*ProjectOperation) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type Operation struct {
	// Types that are valid to be assigned to ProjectOrCredentialOp:
	//	*Operation_ProjectOp
	//	*Operation_CredentialOp
	ProjectOrCredentialOp isOperation_ProjectOrCredentialOp `protobuf_oneof:"ProjectOrCredentialOp"`
}

func (m *Operation) Reset()                    { *m = Operation{} }
func (m *Operation) String() string            { return proto.CompactTextString(m) }
func (*Operation) ProtoMessage()               {}
func (*Operation) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type isOperation_ProjectOrCredentialOp interface {
	isOperation_ProjectOrCredentialOp()
}

type Operation_ProjectOp struct {
	ProjectOp *ProjectOperation `protobuf:"bytes,1,opt,name=projectOp,oneof"`
}
type Operation_CredentialOp struct {
	CredentialOp *ProjectCredentialOperation `protobuf:"bytes,2,opt,name=credentialOp,oneof"`
}

func (*Operation_ProjectOp) isOperation_ProjectOrCredentialOp()    {}
func (*Operation_CredentialOp) isOperation_ProjectOrCredentialOp() {}

func (m *Operation) GetProjectOrCredentialOp() isOperation_ProjectOrCredentialOp {
	if m != nil {
		return m.ProjectOrCredentialOp
	}
	return nil
}

func (m *Operation) GetProjectOp() *ProjectOperation {
	if x, ok := m.GetProjectOrCredentialOp().(*Operation_ProjectOp); ok {
		return x.ProjectOp
	}
	return nil
}

func (m *Operation) GetCredentialOp() *ProjectCredentialOperation {
	if x, ok := m.GetProjectOrCredentialOp().(*Operation_CredentialOp); ok {
		return x.CredentialOp
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*Operation) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _Operation_OneofMarshaler, _Operation_OneofUnmarshaler, _Operation_OneofSizer, []interface{}{
		(*Operation_ProjectOp)(nil),
		(*Operation_CredentialOp)(nil),
	}
}

func _Operation_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*Operation)
	// ProjectOrCredentialOp
	switch x := m.ProjectOrCredentialOp.(type) {
	case *Operation_ProjectOp:
		b.EncodeVarint(1<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.ProjectOp); err != nil {
			return err
		}
	case *Operation_CredentialOp:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.CredentialOp); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("Operation.ProjectOrCredentialOp has unexpected type %T", x)
	}
	return nil
}

func _Operation_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*Operation)
	switch tag {
	case 1: // ProjectOrCredentialOp.projectOp
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(ProjectOperation)
		err := b.DecodeMessage(msg)
		m.ProjectOrCredentialOp = &Operation_ProjectOp{msg}
		return true, err
	case 2: // ProjectOrCredentialOp.credentialOp
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(ProjectCredentialOperation)
		err := b.DecodeMessage(msg)
		m.ProjectOrCredentialOp = &Operation_CredentialOp{msg}
		return true, err
	default:
		return false, nil
	}
}

func _Operation_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*Operation)
	// ProjectOrCredentialOp
	switch x := m.ProjectOrCredentialOp.(type) {
	case *Operation_ProjectOp:
		s := proto.Size(x.ProjectOp)
		n += proto.SizeVarint(1<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Operation_CredentialOp:
		s := proto.Size(x.CredentialOp)
		n += proto.SizeVarint(2<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type Credential struct {
	Id     int32  `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Key    string `protobuf:"bytes,2,opt,name=key" json:"key,omitempty"`
	Cipher string `protobuf:"bytes,3,opt,name=cipher" json:"cipher,omitempty"`
}

func (m *Credential) Reset()                    { *m = Credential{} }
func (m *Credential) String() string            { return proto.CompactTextString(m) }
func (*Credential) ProtoMessage()               {}
func (*Credential) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

type Project struct {
	Id          int32  `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Name        string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Environment string `protobuf:"bytes,3,opt,name=environment" json:"environment,omitempty"`
}

func (m *Project) Reset()                    { *m = Project{} }
func (m *Project) String() string            { return proto.CompactTextString(m) }
func (*Project) ProtoMessage()               {}
func (*Project) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

type ProjectOperationResponse struct {
	Project     *Project      `protobuf:"bytes,1,opt,name=project" json:"project,omitempty"`
	MemberId    int32         `protobuf:"varint,2,opt,name=memberId" json:"memberId,omitempty"`
	Credentials []*Credential `protobuf:"bytes,3,rep,name=credentials" json:"credentials,omitempty"`
}

func (m *ProjectOperationResponse) Reset()                    { *m = ProjectOperationResponse{} }
func (m *ProjectOperationResponse) String() string            { return proto.CompactTextString(m) }
func (*ProjectOperationResponse) ProtoMessage()               {}
func (*ProjectOperationResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *ProjectOperationResponse) GetProject() *Project {
	if m != nil {
		return m.Project
	}
	return nil
}

func (m *ProjectOperationResponse) GetCredentials() []*Credential {
	if m != nil {
		return m.Credentials
	}
	return nil
}

type CredentialOperationResponse struct {
	Credential *Credential `protobuf:"bytes,1,opt,name=credential" json:"credential,omitempty"`
}

func (m *CredentialOperationResponse) Reset()                    { *m = CredentialOperationResponse{} }
func (m *CredentialOperationResponse) String() string            { return proto.CompactTextString(m) }
func (*CredentialOperationResponse) ProtoMessage()               {}
func (*CredentialOperationResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *CredentialOperationResponse) GetCredential() *Credential {
	if m != nil {
		return m.Credential
	}
	return nil
}

type Response struct {
	Status Response_Status `protobuf:"varint,1,opt,name=status,enum=crypto_pb.Response_Status" json:"status,omitempty"`
	Error  string          `protobuf:"bytes,2,opt,name=error" json:"error,omitempty"`
	// Types that are valid to be assigned to ProjectOrCredentialResponse:
	//	*Response_ProjectOpResponse
	//	*Response_CredentialOpResponse
	ProjectOrCredentialResponse isResponse_ProjectOrCredentialResponse `protobuf_oneof:"ProjectOrCredentialResponse"`
}

func (m *Response) Reset()                    { *m = Response{} }
func (m *Response) String() string            { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()               {}
func (*Response) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

type isResponse_ProjectOrCredentialResponse interface {
	isResponse_ProjectOrCredentialResponse()
}

type Response_ProjectOpResponse struct {
	ProjectOpResponse *ProjectOperationResponse `protobuf:"bytes,3,opt,name=projectOpResponse,oneof"`
}
type Response_CredentialOpResponse struct {
	CredentialOpResponse *CredentialOperationResponse `protobuf:"bytes,4,opt,name=credentialOpResponse,oneof"`
}

func (*Response_ProjectOpResponse) isResponse_ProjectOrCredentialResponse()    {}
func (*Response_CredentialOpResponse) isResponse_ProjectOrCredentialResponse() {}

func (m *Response) GetProjectOrCredentialResponse() isResponse_ProjectOrCredentialResponse {
	if m != nil {
		return m.ProjectOrCredentialResponse
	}
	return nil
}

func (m *Response) GetProjectOpResponse() *ProjectOperationResponse {
	if x, ok := m.GetProjectOrCredentialResponse().(*Response_ProjectOpResponse); ok {
		return x.ProjectOpResponse
	}
	return nil
}

func (m *Response) GetCredentialOpResponse() *CredentialOperationResponse {
	if x, ok := m.GetProjectOrCredentialResponse().(*Response_CredentialOpResponse); ok {
		return x.CredentialOpResponse
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*Response) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _Response_OneofMarshaler, _Response_OneofUnmarshaler, _Response_OneofSizer, []interface{}{
		(*Response_ProjectOpResponse)(nil),
		(*Response_CredentialOpResponse)(nil),
	}
}

func _Response_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*Response)
	// ProjectOrCredentialResponse
	switch x := m.ProjectOrCredentialResponse.(type) {
	case *Response_ProjectOpResponse:
		b.EncodeVarint(3<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.ProjectOpResponse); err != nil {
			return err
		}
	case *Response_CredentialOpResponse:
		b.EncodeVarint(4<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.CredentialOpResponse); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("Response.ProjectOrCredentialResponse has unexpected type %T", x)
	}
	return nil
}

func _Response_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*Response)
	switch tag {
	case 3: // ProjectOrCredentialResponse.projectOpResponse
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(ProjectOperationResponse)
		err := b.DecodeMessage(msg)
		m.ProjectOrCredentialResponse = &Response_ProjectOpResponse{msg}
		return true, err
	case 4: // ProjectOrCredentialResponse.credentialOpResponse
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(CredentialOperationResponse)
		err := b.DecodeMessage(msg)
		m.ProjectOrCredentialResponse = &Response_CredentialOpResponse{msg}
		return true, err
	default:
		return false, nil
	}
}

func _Response_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*Response)
	// ProjectOrCredentialResponse
	switch x := m.ProjectOrCredentialResponse.(type) {
	case *Response_ProjectOpResponse:
		s := proto.Size(x.ProjectOpResponse)
		n += proto.SizeVarint(3<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Response_CredentialOpResponse:
		s := proto.Size(x.CredentialOpResponse)
		n += proto.SizeVarint(4<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

func init() {
	proto.RegisterType((*ProjectCredentialOperation)(nil), "crypto_pb.ProjectCredentialOperation")
	proto.RegisterType((*ProjectOperation)(nil), "crypto_pb.ProjectOperation")
	proto.RegisterType((*Operation)(nil), "crypto_pb.Operation")
	proto.RegisterType((*Credential)(nil), "crypto_pb.Credential")
	proto.RegisterType((*Project)(nil), "crypto_pb.Project")
	proto.RegisterType((*ProjectOperationResponse)(nil), "crypto_pb.ProjectOperationResponse")
	proto.RegisterType((*CredentialOperationResponse)(nil), "crypto_pb.CredentialOperationResponse")
	proto.RegisterType((*Response)(nil), "crypto_pb.Response")
	proto.RegisterEnum("crypto_pb.ProjectCredentialOperation_Command", ProjectCredentialOperation_Command_name, ProjectCredentialOperation_Command_value)
	proto.RegisterEnum("crypto_pb.ProjectOperation_Command", ProjectOperation_Command_name, ProjectOperation_Command_value)
	proto.RegisterEnum("crypto_pb.Response_Status", Response_Status_name, Response_Status_value)
}

func init() { proto.RegisterFile("project.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 623 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x9c, 0x54, 0xcb, 0x6e, 0xd3, 0x40,
	0x14, 0xad, 0x9d, 0xd8, 0xae, 0xaf, 0x69, 0xe5, 0x8e, 0x5a, 0xb0, 0x5a, 0x90, 0x2a, 0x23, 0x1e,
	0x0b, 0xc8, 0x22, 0x08, 0xb1, 0x40, 0x2c, 0xf2, 0x30, 0x25, 0x22, 0x25, 0xd5, 0x38, 0xdd, 0x21,
	0x45, 0x8e, 0x33, 0x88, 0x40, 0xfc, 0x90, 0xed, 0x44, 0xea, 0xc7, 0xf0, 0x0b, 0x7c, 0x07, 0x4b,
	0xfe, 0x81, 0x1f, 0x61, 0x3c, 0x1e, 0x7b, 0xdc, 0x24, 0x8d, 0x10, 0x2b, 0xdf, 0xe7, 0x99, 0x7b,
	0xcf, 0x9c, 0x31, 0x1c, 0xc4, 0x49, 0xf4, 0x8d, 0xf8, 0x59, 0x8b, 0x7e, 0xb3, 0x08, 0xe9, 0x7e,
	0x72, 0x13, 0x67, 0xd1, 0x24, 0x9e, 0xda, 0xbf, 0x25, 0x38, 0xbd, 0x2a, 0x92, 0xbd, 0x84, 0xcc,
	0x48, 0x98, 0xcd, 0xbd, 0xc5, 0x28, 0x26, 0x89, 0x97, 0xcd, 0xa3, 0x10, 0x5d, 0x80, 0xe6, 0x47,
	0x41, 0xe0, 0x85, 0x33, 0x4b, 0x3a, 0x97, 0x9e, 0x1f, 0xb6, 0x5f, 0xb6, 0xaa, 0xde, 0xd6, 0xdd,
	0x7d, 0xad, 0x5e, 0xd1, 0x84, 0xcb, 0x6e, 0x64, 0x81, 0xc6, 0x67, 0xb0, 0x64, 0x0a, 0xa4, 0xe0,
	0xd2, 0x45, 0x26, 0x34, 0xbe, 0x93, 0x1b, 0xab, 0x41, 0xa3, 0x3a, 0xce, 0x4d, 0x74, 0x0c, 0xca,
	0xca, 0x5b, 0x2c, 0x89, 0xd5, 0x64, 0xb1, 0xc2, 0xb1, 0x9f, 0x81, 0xc6, 0x51, 0x91, 0x06, 0x8d,
	0x0b, 0x67, 0x6c, 0xee, 0xe5, 0x86, 0x4b, 0x0d, 0x09, 0x01, 0xa8, 0x7d, 0x67, 0xe8, 0x8c, 0x1d,
	0x53, 0xb6, 0xff, 0xc8, 0x60, 0xf2, 0xd1, 0xc4, 0x22, 0xef, 0xd6, 0x17, 0x79, 0xbc, 0xb9, 0xc8,
	0x8e, 0xf1, 0x11, 0x34, 0x43, 0x2f, 0x20, 0x6c, 0x76, 0x1d, 0x33, 0x1b, 0x9d, 0x83, 0x41, 0xc2,
	0xd5, 0x3c, 0x89, 0xc2, 0x80, 0xae, 0xcf, 0x17, 0xa8, 0x87, 0xd0, 0x43, 0xd0, 0xf9, 0x96, 0x83,
	0x19, 0x5b, 0x46, 0xc1, 0x22, 0x80, 0x4e, 0x61, 0x3f, 0x20, 0xc1, 0x94, 0x24, 0x34, 0xa9, 0xb0,
	0x64, 0xe5, 0xa3, 0xfb, 0xa0, 0x2e, 0x53, 0x96, 0x51, 0x59, 0x86, 0x7b, 0xf9, 0x99, 0x9e, 0xef,
	0x93, 0x34, 0x1d, 0x92, 0x15, 0x59, 0x58, 0x5a, 0x71, 0x66, 0x2d, 0x64, 0x7f, 0x11, 0x34, 0x51,
	0x52, 0x7a, 0xd8, 0xe9, 0x50, 0x52, 0xf6, 0x72, 0xfb, 0xfa, 0xaa, 0x9f, 0xdb, 0xb7, 0xc8, 0x42,
	0x87, 0x00, 0x9d, 0x7e, 0x7f, 0x72, 0xe9, 0x5c, 0x76, 0x1d, 0x6c, 0x36, 0xd0, 0x11, 0x1c, 0x14,
	0xb9, 0x32, 0xd4, 0xa4, 0xd7, 0x61, 0x0e, 0x07, 0xee, 0x78, 0x42, 0xb1, 0xfa, 0xce, 0xa7, 0xf1,
	0xa0, 0x33, 0x74, 0x4d, 0xc5, 0xfe, 0x29, 0x81, 0x2e, 0xe8, 0x7d, 0x5b, 0x6d, 0x3a, 0x8a, 0x19,
	0xc1, 0x46, 0xfb, 0x6c, 0x07, 0xc1, 0x1f, 0xf6, 0xb0, 0xa8, 0x47, 0x1f, 0xe1, 0x9e, 0x5f, 0xd3,
	0x10, 0x23, 0xd9, 0x68, 0x3f, 0xf9, 0x27, 0xa5, 0x51, 0xa4, 0x5b, 0xcd, 0xdd, 0x07, 0x70, 0x52,
	0x9e, 0x96, 0xd4, 0xeb, 0xed, 0xf7, 0x00, 0xc2, 0xa7, 0x7b, 0xcb, 0xf3, 0x42, 0x0a, 0x0a, 0xa6,
	0x56, 0xa9, 0x42, 0x59, 0xa8, 0x90, 0x5e, 0x81, 0x3f, 0x8f, 0xbf, 0x92, 0x84, 0xdf, 0x2c, 0xf7,
	0xec, 0x11, 0x68, 0xfc, 0x80, 0x0d, 0x90, 0xff, 0x52, 0x89, 0xfd, 0x43, 0x02, 0x6b, 0x9d, 0x20,
	0x4c, 0xd2, 0x38, 0x0a, 0x53, 0x82, 0x5e, 0x88, 0x77, 0x53, 0xd0, 0x8a, 0x36, 0x69, 0x11, 0x6f,
	0xa9, 0x2e, 0x29, 0x79, 0x4d, 0x52, 0x6f, 0xc0, 0x10, 0x44, 0xa5, 0x74, 0x90, 0x06, 0x45, 0x3b,
	0xa9, 0xa1, 0x09, 0x76, 0x70, 0xbd, 0xd2, 0x1e, 0xc3, 0xd9, 0x16, 0xe2, 0xab, 0x09, 0x5f, 0x03,
	0x88, 0x6a, 0x3e, 0xe4, 0x1d, 0xb0, 0xb5, 0x42, 0xfb, 0x97, 0x0c, 0xfb, 0x15, 0x46, 0x1b, 0xd4,
	0x34, 0xf3, 0xb2, 0x65, 0xca, 0x1f, 0xe7, 0x69, 0xad, 0xbf, 0x2c, 0x6a, 0xb9, 0xac, 0x02, 0xf3,
	0xca, 0xfc, 0x2f, 0x41, 0x92, 0x24, 0x4a, 0x38, 0xdb, 0x85, 0x83, 0x5c, 0x38, 0xaa, 0x84, 0x55,
	0x76, 0x32, 0xd2, 0x8d, 0x9d, 0x2f, 0xbe, 0x2c, 0xa5, 0x72, 0xda, 0xec, 0x47, 0x9f, 0xe1, 0xb8,
	0xae, 0xb1, 0x0a, 0xb7, 0xc9, 0x70, 0x9f, 0x6e, 0x5d, 0x76, 0x1b, 0xf4, 0x56, 0x14, 0xfb, 0x1c,
	0xd4, 0x62, 0x35, 0xa4, 0x83, 0xe2, 0x60, 0x3c, 0xc2, 0xf4, 0xbd, 0x1a, 0xa0, 0xb9, 0xd7, 0xbd,
	0x9e, 0xe3, 0xba, 0xa6, 0xd4, 0x7d, 0x04, 0x67, 0x5b, 0x34, 0x5d, 0x02, 0x4c, 0x55, 0xf6, 0x57,
	0x7f, 0xf5, 0x37, 0x00, 0x00, 0xff, 0xff, 0x45, 0x76, 0x59, 0xb9, 0xe6, 0x05, 0x00, 0x00,
}
