// Code generated by protoc-gen-go.
// source: project.proto
// DO NOT EDIT!

/*
Package crypto_pb is a generated protocol buffer package.

It is generated from these files:
	project.proto

It has these top-level messages:
	Credential
	ProjectCredentialOperation
*/
package crypto_pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ProjectCredentialOperation_Command int32

const (
	ProjectCredentialOperation_GET    ProjectCredentialOperation_Command = 0
	ProjectCredentialOperation_SET    ProjectCredentialOperation_Command = 1
	ProjectCredentialOperation_DELETE ProjectCredentialOperation_Command = 2
)

var ProjectCredentialOperation_Command_name = map[int32]string{
	0: "GET",
	1: "SET",
	2: "DELETE",
}
var ProjectCredentialOperation_Command_value = map[string]int32{
	"GET":    0,
	"SET":    1,
	"DELETE": 2,
}

func (x ProjectCredentialOperation_Command) String() string {
	return proto.EnumName(ProjectCredentialOperation_Command_name, int32(x))
}
func (ProjectCredentialOperation_Command) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor0, []int{1, 0}
}

type Credential struct {
	Project int32  `protobuf:"varint,1,opt,name=project" json:"project,omitempty"`
	Key     string `protobuf:"bytes,2,opt,name=key" json:"key,omitempty"`
	Value   string `protobuf:"bytes,3,opt,name=value" json:"value,omitempty"`
}

func (m *Credential) Reset()                    { *m = Credential{} }
func (m *Credential) String() string            { return proto.CompactTextString(m) }
func (*Credential) ProtoMessage()               {}
func (*Credential) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type ProjectCredentialOperation struct {
	Command     ProjectCredentialOperation_Command `protobuf:"varint,1,opt,name=command,enum=crypto_pb.ProjectCredentialOperation_Command" json:"command,omitempty"`
	Credentials []*Credential                      `protobuf:"bytes,2,rep,name=credentials" json:"credentials,omitempty"`
}

func (m *ProjectCredentialOperation) Reset()                    { *m = ProjectCredentialOperation{} }
func (m *ProjectCredentialOperation) String() string            { return proto.CompactTextString(m) }
func (*ProjectCredentialOperation) ProtoMessage()               {}
func (*ProjectCredentialOperation) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *ProjectCredentialOperation) GetCredentials() []*Credential {
	if m != nil {
		return m.Credentials
	}
	return nil
}

func init() {
	proto.RegisterType((*Credential)(nil), "crypto_pb.Credential")
	proto.RegisterType((*ProjectCredentialOperation)(nil), "crypto_pb.ProjectCredentialOperation")
	proto.RegisterEnum("crypto_pb.ProjectCredentialOperation_Command", ProjectCredentialOperation_Command_name, ProjectCredentialOperation_Command_value)
}

func init() { proto.RegisterFile("project.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 216 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0x2d, 0x28, 0xca, 0xcf,
	0x4a, 0x4d, 0x2e, 0xd1, 0x03, 0xd2, 0x25, 0xf9, 0x42, 0x9c, 0xc9, 0x45, 0x95, 0x05, 0x25, 0xf9,
	0xf1, 0x05, 0x49, 0x4a, 0x7e, 0x5c, 0x5c, 0xce, 0x45, 0xa9, 0x29, 0xa9, 0x79, 0x25, 0x99, 0x89,
	0x39, 0x42, 0x12, 0x5c, 0xec, 0x50, 0x95, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0xac, 0x41, 0x30, 0xae,
	0x90, 0x00, 0x17, 0x73, 0x76, 0x6a, 0xa5, 0x04, 0x13, 0x50, 0x94, 0x33, 0x08, 0xc4, 0x14, 0x12,
	0xe1, 0x62, 0x2d, 0x4b, 0xcc, 0x29, 0x4d, 0x95, 0x60, 0x06, 0x8b, 0x41, 0x38, 0x4a, 0xc7, 0x19,
	0xb9, 0xa4, 0x02, 0x20, 0x7a, 0x10, 0xe6, 0xfa, 0x17, 0xa4, 0x16, 0x25, 0x96, 0x64, 0xe6, 0xe7,
	0x09, 0xb9, 0x73, 0xb1, 0x27, 0xe7, 0xe7, 0xe6, 0x26, 0xe6, 0xa5, 0x80, 0x2d, 0xe0, 0x33, 0xd2,
	0xd5, 0x83, 0xbb, 0x45, 0x0f, 0xb7, 0x3e, 0x3d, 0x67, 0x88, 0xa6, 0x20, 0x98, 0x6e, 0x21, 0x73,
	0x2e, 0xee, 0x64, 0xb8, 0xba, 0x62, 0xa0, 0xbb, 0x98, 0x35, 0xb8, 0x8d, 0x44, 0x91, 0x0c, 0x43,
	0x98, 0x12, 0x84, 0xac, 0x52, 0x49, 0x9d, 0x8b, 0x1d, 0x6a, 0x98, 0x10, 0x3b, 0x17, 0xb3, 0xbb,
	0x6b, 0x88, 0x00, 0x03, 0x88, 0x11, 0x0c, 0x64, 0x30, 0x0a, 0x71, 0x71, 0xb1, 0xb9, 0xb8, 0xfa,
	0xb8, 0x86, 0xb8, 0x0a, 0x30, 0x25, 0xb1, 0x81, 0xc3, 0xca, 0x18, 0x10, 0x00, 0x00, 0xff, 0xff,
	0xfd, 0xfd, 0x53, 0x78, 0x3c, 0x01, 0x00, 0x00,
}
